# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Devendra Tomar
title: Data and Application Architect | Azure Big Data SME 
email: devendra.tomar.04@gmail.com
website: https://github.com/DevendraTomar

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: DevendraTomar
linkedin_username: devendratomar04

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced Azure Data Architect with 12+ years in the field, specializing in designing and implementing advanced data solutions on the Microsoft Azure platform. My core expertise is in creating scalable and efficient big data architectures that empower businesses to derive actionable insights from large datasets.

  With a solid background in researching and evaluating emerging Big Data and Gen AI technologies, I also bring extensive experience in developing ETL pipelines and architecting Data Lakehouse/Data Mesh solutions.

  I excel in collaborative environments and am dedicated to building strong relationships with teams and stakeholders to ensure the success of every project.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Tiger Analytics
        link: https://www.tigeranalytics.com
        sub_title: Data and Application Architect
        caption: December 2021 - Present
        description: | # this will include new lines to allow paragraphs
          • Architected and implemented a modern data lakehouse on Azure using Databricks, enabling self-service and governance.

          • Designed and developed metadata-driven data pipelines for ingestion, transformation, and quality checks.

          • Integrated Azure OpenAI services to automate SQL query generation and data quality rule recommendations.
      - layout: left
        title: Optum
        link: https://www.optum.com
        sub_title: Lead Software Engineer
        caption: February 2021 - December 2021
        description: | # this will include new lines to allow paragraphs
          • Led the development of a YAML-based data pipeline for Big Query, enhancing data discovery and governance.

          • Spearheaded the end-to-end orchestration of a real-time data migration solution using Cloud Composer and Kafka.
      - layout: left
        title: Coforge
        link: https://www.coforge.com
        sub_title: Technical Analyst
        caption: December 2018 - January 2021
        description: | # this will include new lines to allow paragraphs
            Designed and implemented an Azure-based Data Lake for a UK-based telecom client, conducting research and development of various tools (IaaS, PaaS) for real-time and batch data processing on Azure. Augmented Azure Data Factory ingestion pipelines to perform incremental ingestion between different sources. Conducted research and development on creating data lakes using Docker containers for on-premise systems and handled change data capture (CDC) in near real-time using open-source technologies.
      - layout: left
        title: Sapient Global Markets
        link: https://www.publicissapient.com
        sub_title: Senior Associate
        caption: August 2016 - November 2018
        description: | # this will include new lines to allow paragraphs
          Developed Spark applications for processing XML and flat data files from S3, converting them into a fixed-width format backed by an external Hive table for queryability. Created data ingestion and transformation pipelines in NiFi, integrating multiple sources like RabbitMQ, S3, and File System, and designed the corresponding data model in Hive. Developed custom NiFi processors for running Hive queries and utility processors for various tasks. Enhanced the Data Lake's global search feature for metadata and actual data searches. Developed a chatbot QnA service using an ontology and Elasticsearch, and created/modifed NiFi templates based on business requirements.
      - layout: left
        title: NEC Technologies India Ltd.
        link: https://in.nec.com
        sub_title: Senior MTS
        caption: December 2012 - July 2016
        description: | # this will include new lines to allow paragraphs
          Developed and tested multi-threaded client-server applications for file exchange, migrated service layer code from BEA WebLogic Workshop to Java, created new electronic banking screens, and performed unit testing. Additionally, developed test tools and modules for managing web servers and UNC service layer APIs.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Uttarakhand Technical University
        caption: 2008 - 2012
        sub_title: Bachelor's Degree, Computer Science
      - layout: left
        title: Amtul's Public School, Nainital
        caption: 2006 - 2008
        sub_title: Computer Science

  - title: Top Skills
    layout: grid
    content:
      - layout: center
        title: Data Engineering
      - layout: center
        title: Generative AI
      - layout: center
        title: Application Engineering
      - layout: center
        title: System Design

  - title: Certifications
    layout: grid
    content:
      - layout: center
        title: Databricks Certified Data Engineer Professional
      - layout: center
        title: Databricks Certified Data Engineer Associate
      - layout: center
        title: Astronomer Certification for Apache Airflow
      - layout: center
        title: Oracle Certified Java Programmer (OCJP)
      - layout: center
        title: Azure DP 200 - Implementing an Azure Data Solution  

  - title: Honors-Awards
    layout: list
    content:
      - layout: center
        title: Coforge - Emerging Performer of the Year
      - layout: center
        title: Publicis Sapient - You Make a Difference
      - layout: center
        title: NEC - Award of Excellence

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
